version: '3'

services:
    jenkins:
        user: root
        image: 192.168.0.30:5000/api-jenkins:latest
        ports:
         - "8082:8080"
         - "50000:50000"
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /volumenes/vol_jenkins:/var/jenkins_home
        environment:
         - JENKINS_ADMIN_ID=admin
         - JENKINS_ADMIN_PASSWORD=admin
         - IP_REGISTRY=192.168.0.30
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                 - "node.role==manager"
    
